name: Test Junit on Pull

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Use mvnw so consistent versions of maven is used
      - name: Build with Gradle
        run: ./mvnw install

      - name: Run JUnit tests
        run: ./mvnw test

